CREATE TABLE chat_public_log_tb (
    created_at TIMESTAMP(6) DEFAULT NOW(),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ip VARCHAR(20),
    output TEXT,
    request_message TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE chatroom_tb (
    created_at TIMESTAMP(6) DEFAULT NOW(),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    title VARCHAR(50),
    PRIMARY KEY (id)
);
CREATE TABLE email_verification_tb (
    created_at TIMESTAMP(6) DEFAULT NOW(),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    verification_code VARCHAR(10) NOT NULL,
    email VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE favor_tb (
    created_at TIMESTAMP(6) DEFAULT NOW(),
    food_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT,
    PRIMARY KEY (id)
);

CREATE TABLE food_tb (
    spicy INTEGER NOT NULL,
    created_at TIMESTAMP(6) DEFAULT NOW(),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    country VARCHAR(50) NOT NULL,
    flavor VARCHAR(50) NOT NULL,
    ingredient VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    oily VARCHAR(50) NOT NULL,
    temperature VARCHAR(50) NOT NULL,
    image_url VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE message_tb (
    is_from_chatbot BOOLEAN NOT NULL,
    chatroom_id BIGINT,
    created_at TIMESTAMP(6) DEFAULT NOW(),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content TEXT,
    PRIMARY KEY (id)
);

CREATE TABLE user_tb (
    birth DATE DEFAULT '2000-01-01',
    gender BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) DEFAULT NOW(),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login_id VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(40) DEFAULT '회원',
    role VARCHAR(50) DEFAULT 'ROLE_PENDING' CHECK (role IN ('ROLE_PENDING','ROLE_USER')),
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);
